# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Single-marker association test based on the chi-squared statistic
#' @param ccdata A matrix of markers (columns) and individuals (rows).  Data are coded as the number of copies of the minor allele.
#' @param ccstatus A vector of discrete phenotype labels.  0 = control, 1 = case.
#' @return A vector of -log10(p-values) from a chi-squared test with one degree of freedom.
chisq_per_marker <- function(ccdata, ccstatus) {
    .Call('buRden_chisq_per_marker', PACKAGE = 'buRden', ccdata, ccstatus)
}

#' Apply frequency and LD filters to a genotype matrix
#' @param ccdata A matrix of markers (columns) and individuals (rows).  Data are coded as the number of copies of the minor allele.
#' @param ccstatus A vector of discrete phenotype labels.  0 = control, 1 = case.
#' @param minfreq A site with minor allele frequency < minfreq will not be kept.
#' @param maxfreq A site with minor allele frequency > maxfreq will not be kept.
#' @param rsq_cutoff  When comparing two sites, if the genotype correlation coefficient r^2 is >= rsq_cutoff, only the first site will be kept.
#' @return A vector of integers containing the values 0 (not kept) and 1 (kept).  The length of the vector is equal to the number of columns in ccdata.
#' @details Regarding rsq_cutoff, when sites i and j are compared (j > i), site i will be kept and site j will not be kept.
filter_sites <- function(ccdata, ccstatus, minfreq, maxfreq, rsq_cutoff) {
    .Call('buRden_filter_sites', PACKAGE = 'buRden', ccdata, ccstatus, minfreq, maxfreq, rsq_cutoff)
}

#' Association stat from Thornton, Foran, and Long (2013) PLoS Genetics
#' @param A vector of single-marker association test scores, on a -log10 scale
#' @param K the number of markers used to calculate ESM_K
#' @return The ESM_K test statistic value
#' @note See http://www.ncbi.nlm.nih.gov/pubmed/23437004 for detail on the test statistic
esm <- function(scores, K) {
    .Call('buRden_esm', PACKAGE = 'buRden', scores, K)
}

#' Pearson's product-moment correlation
#' @param x A vector of values.
#' @param y A vector of values.
#' @return The correlation coefficient between x and y. This should/will be equal to R's cor(x,y).
#' @note This implementation is based on a copy of [libsequence's](http://github.com/molpopgen/libsequence) template function object Sequence::ProductMoment in <Sequence/Correlations.hpp>
ProductMoment <- function(x, y) {
    .Call('buRden_ProductMoment', PACKAGE = 'buRden', x, y)
}

